<?php

/*
 * Il listino del Manuale del DM, dall'SRD 5.1 (licenza CC-BY-4.0, Wizards of the Coast).
 * Prezzi in rame: 1 mo = 100 mr. Separato dall'Emporio: non tocca i prezzi veri.
 */

return [
    'Equipaggiamento' => [
        'Acciarino e pietra focaia' => 50,
        'Ampolla di olio' => 10,
        'Arnesi da scasso' => 2_500,
        'Attrezzatura da scalatore' => 2_500,
        'Borraccia' => 20,
        'Candela' => 1,
        'Catena (3 m)' => 500,
        'Coperta' => 50,
        'Corda di canapa (15 m)' => 100,
        'Corda di seta (15 m)' => 1_000,
        'Fiaccola' => 1,
        'Gessetto' => 1,
        'Kit da guaritore' => 500,
        'Lanterna a lente sporgente' => 1_000,
        'Lanterna schermabile' => 500,
        'Libro' => 2_500,
        'Lucchetto' => 1_000,
        'Manette' => 200,
        'Martello' => 100,
        'Pala' => 200,
        'Pergamena (un foglio)' => 10,
        'Piede di porco' => 200,
        'Razioni (1 giorno)' => 50,
        'Sacco a pelo' => 100,
        'Specchio d\'acciaio' => 500,
        'Tenda per due' => 200,
        'Zaino' => 200,
        'Acido (fiala)' => 2_500,
        'Acqua santa (ampolla)' => 2_500,
        'Antidoto (fiala)' => 5_000,
        'Fuoco dell\'alchimista (ampolla)' => 5_000,
        'Pozione di guarigione' => 5_000,
        'Veleno base (fiala)' => 10_000,
    ],
    'Vitto e alloggio' => [
        'Pasto squallido' => 3,
        'Pasto povero' => 6,
        'Pasto modesto' => 30,
        'Pasto agiato' => 50,
        'Pasto ricco' => 80,
        'Pasto aristocratico' => 200,
        'Notte in locanda squallida' => 7,
        'Notte in locanda povera' => 10,
        'Notte in locanda modesta' => 50,
        'Notte in locanda agiata' => 80,
        'Notte in locanda ricca' => 200,
        'Notte in locanda aristocratica' => 400,
        'Boccale di birra' => 4,
        'Brocca di birra' => 20,
        'Bottiglia di vino comune' => 20,
        'Bottiglia di vino pregiato' => 1_000,
    ],
    'Servizi' => [
        'Cocchiere in città' => 1,
        'Cocchiere fra città (per 1,5 km)' => 3,
        'Messaggero (per 1,5 km)' => 2,
        'Pedaggio di strada o porta' => 1,
        'Passaggio in nave (per 1,5 km)' => 10,
        'Mercenario non addestrato (al giorno)' => 20,
        'Mercenario addestrato (al giorno)' => 200,
    ],
    'Incantesimi a pagamento' => [
        'Trucchetto' => 1_000,
        'Incantesimo di 1° livello' => 5_000,
        'Incantesimo di 2° livello' => 10_000,
        'Incantesimo di 3° livello' => 20_000,
    ],
    'Cavalcature e veicoli' => [
        'Asino o mulo' => 800,
        'Cavallo da tiro' => 5_000,
        'Cavallo da sella' => 7_500,
        'Cavallo da guerra' => 40_000,
        'Pony' => 3_000,
        'Mastino' => 2_500,
        'Carretto' => 1_500,
        'Carro' => 3_500,
        'Carrozza' => 10_000,
        'Barca a remi' => 5_000,
        'Sella da viaggio' => 1_000,
        'Foraggio (al giorno)' => 5,
        'Stalla (al giorno)' => 50,
    ],
];
